# permissions for end users to edit tests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: test-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator-kubebuilder-clientset
    app.kubernetes.io/part-of: operator-kubebuilder-clientset
    app.kubernetes.io/managed-by: kustomize
  name: test-editor-role
rules:
- apiGroups:
  - job.lailin.xyz
  resources:
  - tests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - job.lailin.xyz
  resources:
  - tests/status
  verbs:
  - get
